ci: refine comments in orangefox.yml for better understanding
Updated comments in orangefox.yml for clarity and consistency.

diff --git a/.github/workflows/orangefox.yml b/.github/workflows/orangefox.yml
--- a/.github/workflows/orangefox.yml
+++ b/.github/workflows/orangefox.yml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
     inputs:
       MANIFEST_BRANCH:
-        description: 'OrangeFox Branch (Pilih Angkanya Saja: 12.1 / 11.0)'
+        description: 'OrangeFox Branch (Pick the Numbers Only: 12.1 / 11.0)'
         required: true
         default: '12.1'
         type: choice
@@ -89,23 +89,32 @@ jobs:
         git clone https://gitlab.com/OrangeFox/sync.git
         cd sync
         
-        # Eksekusi sinkronisasi
+        # Synchronization execution
         ./orangefox_sync.sh --branch ${{ github.event.inputs.MANIFEST_BRANCH }} --path ${{ github.workspace }}/OrangeFox
 
     - name: Clone Device Tree
       run: |
-        # Langsung masuk ke folder OrangeFox utama
+        # Go directly to the main OrangeFox folder
         cd ${{ github.workspace }}/OrangeFox
         git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ${{ github.event.inputs.DEVICE_PATH }}
 
     - name: Build OrangeFox
       run: |
-        # Eksekusi Build di folder OrangeFox
         cd ${{ github.workspace }}/OrangeFox
+        
+        # 1. Temporarily turn off strict mode so that minor errors in vendorsetup.sh are ignored.
+        set +e
+        
+        # 2. Initialize environment & lunch
         source build/envsetup.sh
         export ALLOW_MISSING_DEPENDENCIES=true
         export LC_ALL="C"
         lunch ${{ github.event.inputs.MAKEFILE_NAME }}_${{ github.event.inputs.DEVICE_NAME }}-eng
+        
+        # 3.  Turn strict mode back on so that if compilation fails, the log is read.
+        set -e
+        
+        # 4. Start compiling
         mka adbd ${{ github.event.inputs.BUILD_TARGET }}
 
     - name: Upload Build Artifacts
